### ISSUE TITLE
fonts won't load properly 

### ISSUE THREAD

**Issue by lcundiff** [Gator-Bytes-Foundation/p4hApp#25]
font awesome gives errors because of regex syntax or something. Its related to the config for the webpack.

**Comment by MainShayne233** [comment]
@lcundiff Could you show me the error you're getting for this? When I uncomment the `import` for font-awesome and load a page with a font-awesome icon it successfully loads.

**Comment by lcundiff** [comment]
Forget how this was fixed, but I think it might have been a Linux to Windows issue?
